rover_node:
  ros__parameters:

    wheels:
      separation: 0.160
      radius: 0.033

    motors:
      profile_acceleration_constant: 214.577
      profile_acceleration: 0.0

    sensors:
      bumper_1: false
      bumper_2: false

      illumination: false

      ir: false

      sonar: false

diff_drive_controller:
  ros__parameters:

    odometry:
      publish_tf: true
      use_imu: true
      frame_id: "odom"
      child_frame_id: "base_link"